language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install --prefer-dist --no-progress --no-suggest

script:
  - composer test
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/vendor
