language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - hhvm # on Trusty only
  - nightly
  
install:
  - composer install --prefer-dist --no-progress --no-suggest
  
script:
  - composer test
