language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4snapshot'
  - nightly
  
jobs:
  fast_finish: true
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  
install:
  - composer install --prefer-dist --no-progress --no-suggest
  
script:
  - composer test
